# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ctet_smu_measurement_service_pb2 as ctet__smu__measurement__service__pb2


class MeasurementServiceStub(object):
    """---------------------------------------------------------------------
    The MeasurementService service definition.
    ---------------------------------------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Invoke = channel.unary_unary(
                '/measurementservice.MeasurementService/Invoke',
                request_serializer=ctet__smu__measurement__service__pb2.InvokeRequest.SerializeToString,
                response_deserializer=ctet__smu__measurement__service__pb2.InvokeResponse.FromString,
                )
        self.Query = channel.unary_unary(
                '/measurementservice.MeasurementService/Query',
                request_serializer=ctet__smu__measurement__service__pb2.QueryRequest.SerializeToString,
                response_deserializer=ctet__smu__measurement__service__pb2.QueryResponse.FromString,
                )
        self.Register = channel.unary_stream(
                '/measurementservice.MeasurementService/Register',
                request_serializer=ctet__smu__measurement__service__pb2.RegistrationRequest.SerializeToString,
                response_deserializer=ctet__smu__measurement__service__pb2.ServerEvent.FromString,
                )
        self.OpenSMUSession = channel.unary_unary(
                '/measurementservice.MeasurementService/OpenSMUSession',
                request_serializer=ctet__smu__measurement__service__pb2.SMUOpenSessionRequest.SerializeToString,
                response_deserializer=ctet__smu__measurement__service__pb2.SMUOpenSessionResponse.FromString,
                )
        self.ConfigureSMU = channel.unary_unary(
                '/measurementservice.MeasurementService/ConfigureSMU',
                request_serializer=ctet__smu__measurement__service__pb2.SMUConfigRequest.SerializeToString,
                response_deserializer=ctet__smu__measurement__service__pb2.SMUConfigResponse.FromString,
                )
        self.EnableSMUOutput = channel.unary_unary(
                '/measurementservice.MeasurementService/EnableSMUOutput',
                request_serializer=ctet__smu__measurement__service__pb2.SMUEnableRequest.SerializeToString,
                response_deserializer=ctet__smu__measurement__service__pb2.SMUEnableResponse.FromString,
                )
        self.DisableSMUOutput = channel.unary_unary(
                '/measurementservice.MeasurementService/DisableSMUOutput',
                request_serializer=ctet__smu__measurement__service__pb2.SMUDisableRequest.SerializeToString,
                response_deserializer=ctet__smu__measurement__service__pb2.SMUDisableResponse.FromString,
                )
        self.PerformSMUCurrentMeasurement = channel.unary_unary(
                '/measurementservice.MeasurementService/PerformSMUCurrentMeasurement',
                request_serializer=ctet__smu__measurement__service__pb2.SMUCurrentRequest.SerializeToString,
                response_deserializer=ctet__smu__measurement__service__pb2.SMUCurrentData.FromString,
                )
        self.CloseSMUSession = channel.unary_unary(
                '/measurementservice.MeasurementService/CloseSMUSession',
                request_serializer=ctet__smu__measurement__service__pb2.SMUCloseSessionRequest.SerializeToString,
                response_deserializer=ctet__smu__measurement__service__pb2.SMUCloseSessionResponse.FromString,
                )
        self.SelfCalibrateSMU = channel.unary_unary(
                '/measurementservice.MeasurementService/SelfCalibrateSMU',
                request_serializer=ctet__smu__measurement__service__pb2.SMUSelfCalRequest.SerializeToString,
                response_deserializer=ctet__smu__measurement__service__pb2.SMUSelfCalResponse.FromString,
                )
        self.ResetSMU = channel.unary_unary(
                '/measurementservice.MeasurementService/ResetSMU',
                request_serializer=ctet__smu__measurement__service__pb2.SMUResetRequest.SerializeToString,
                response_deserializer=ctet__smu__measurement__service__pb2.SMUResetResponse.FromString,
                )


class MeasurementServiceServicer(object):
    """---------------------------------------------------------------------
    The MeasurementService service definition.
    ---------------------------------------------------------------------
    """

    def Invoke(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Query(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenSMUSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfigureSMU(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnableSMUOutput(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisableSMUOutput(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PerformSMUCurrentMeasurement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseSMUSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SelfCalibrateSMU(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetSMU(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MeasurementServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Invoke': grpc.unary_unary_rpc_method_handler(
                    servicer.Invoke,
                    request_deserializer=ctet__smu__measurement__service__pb2.InvokeRequest.FromString,
                    response_serializer=ctet__smu__measurement__service__pb2.InvokeResponse.SerializeToString,
            ),
            'Query': grpc.unary_unary_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=ctet__smu__measurement__service__pb2.QueryRequest.FromString,
                    response_serializer=ctet__smu__measurement__service__pb2.QueryResponse.SerializeToString,
            ),
            'Register': grpc.unary_stream_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=ctet__smu__measurement__service__pb2.RegistrationRequest.FromString,
                    response_serializer=ctet__smu__measurement__service__pb2.ServerEvent.SerializeToString,
            ),
            'OpenSMUSession': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenSMUSession,
                    request_deserializer=ctet__smu__measurement__service__pb2.SMUOpenSessionRequest.FromString,
                    response_serializer=ctet__smu__measurement__service__pb2.SMUOpenSessionResponse.SerializeToString,
            ),
            'ConfigureSMU': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfigureSMU,
                    request_deserializer=ctet__smu__measurement__service__pb2.SMUConfigRequest.FromString,
                    response_serializer=ctet__smu__measurement__service__pb2.SMUConfigResponse.SerializeToString,
            ),
            'EnableSMUOutput': grpc.unary_unary_rpc_method_handler(
                    servicer.EnableSMUOutput,
                    request_deserializer=ctet__smu__measurement__service__pb2.SMUEnableRequest.FromString,
                    response_serializer=ctet__smu__measurement__service__pb2.SMUEnableResponse.SerializeToString,
            ),
            'DisableSMUOutput': grpc.unary_unary_rpc_method_handler(
                    servicer.DisableSMUOutput,
                    request_deserializer=ctet__smu__measurement__service__pb2.SMUDisableRequest.FromString,
                    response_serializer=ctet__smu__measurement__service__pb2.SMUDisableResponse.SerializeToString,
            ),
            'PerformSMUCurrentMeasurement': grpc.unary_unary_rpc_method_handler(
                    servicer.PerformSMUCurrentMeasurement,
                    request_deserializer=ctet__smu__measurement__service__pb2.SMUCurrentRequest.FromString,
                    response_serializer=ctet__smu__measurement__service__pb2.SMUCurrentData.SerializeToString,
            ),
            'CloseSMUSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseSMUSession,
                    request_deserializer=ctet__smu__measurement__service__pb2.SMUCloseSessionRequest.FromString,
                    response_serializer=ctet__smu__measurement__service__pb2.SMUCloseSessionResponse.SerializeToString,
            ),
            'SelfCalibrateSMU': grpc.unary_unary_rpc_method_handler(
                    servicer.SelfCalibrateSMU,
                    request_deserializer=ctet__smu__measurement__service__pb2.SMUSelfCalRequest.FromString,
                    response_serializer=ctet__smu__measurement__service__pb2.SMUSelfCalResponse.SerializeToString,
            ),
            'ResetSMU': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetSMU,
                    request_deserializer=ctet__smu__measurement__service__pb2.SMUResetRequest.FromString,
                    response_serializer=ctet__smu__measurement__service__pb2.SMUResetResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'measurementservice.MeasurementService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MeasurementService(object):
    """---------------------------------------------------------------------
    The MeasurementService service definition.
    ---------------------------------------------------------------------
    """

    @staticmethod
    def Invoke(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/measurementservice.MeasurementService/Invoke',
            ctet__smu__measurement__service__pb2.InvokeRequest.SerializeToString,
            ctet__smu__measurement__service__pb2.InvokeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/measurementservice.MeasurementService/Query',
            ctet__smu__measurement__service__pb2.QueryRequest.SerializeToString,
            ctet__smu__measurement__service__pb2.QueryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/measurementservice.MeasurementService/Register',
            ctet__smu__measurement__service__pb2.RegistrationRequest.SerializeToString,
            ctet__smu__measurement__service__pb2.ServerEvent.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def OpenSMUSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/measurementservice.MeasurementService/OpenSMUSession',
            ctet__smu__measurement__service__pb2.SMUOpenSessionRequest.SerializeToString,
            ctet__smu__measurement__service__pb2.SMUOpenSessionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ConfigureSMU(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/measurementservice.MeasurementService/ConfigureSMU',
            ctet__smu__measurement__service__pb2.SMUConfigRequest.SerializeToString,
            ctet__smu__measurement__service__pb2.SMUConfigResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EnableSMUOutput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/measurementservice.MeasurementService/EnableSMUOutput',
            ctet__smu__measurement__service__pb2.SMUEnableRequest.SerializeToString,
            ctet__smu__measurement__service__pb2.SMUEnableResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DisableSMUOutput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/measurementservice.MeasurementService/DisableSMUOutput',
            ctet__smu__measurement__service__pb2.SMUDisableRequest.SerializeToString,
            ctet__smu__measurement__service__pb2.SMUDisableResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PerformSMUCurrentMeasurement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/measurementservice.MeasurementService/PerformSMUCurrentMeasurement',
            ctet__smu__measurement__service__pb2.SMUCurrentRequest.SerializeToString,
            ctet__smu__measurement__service__pb2.SMUCurrentData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CloseSMUSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/measurementservice.MeasurementService/CloseSMUSession',
            ctet__smu__measurement__service__pb2.SMUCloseSessionRequest.SerializeToString,
            ctet__smu__measurement__service__pb2.SMUCloseSessionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SelfCalibrateSMU(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/measurementservice.MeasurementService/SelfCalibrateSMU',
            ctet__smu__measurement__service__pb2.SMUSelfCalRequest.SerializeToString,
            ctet__smu__measurement__service__pb2.SMUSelfCalResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ResetSMU(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/measurementservice.MeasurementService/ResetSMU',
            ctet__smu__measurement__service__pb2.SMUResetRequest.SerializeToString,
            ctet__smu__measurement__service__pb2.SMUResetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
