# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import dio_measurement_service_pb2 as dio__measurement__service__pb2


class MeasurementServiceStub(object):
    """---------------------------------------------------------------------
    The MeasurementService service definition.
    ---------------------------------------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Invoke = channel.unary_unary(
                '/measurementservice.MeasurementService/Invoke',
                request_serializer=dio__measurement__service__pb2.InvokeRequest.SerializeToString,
                response_deserializer=dio__measurement__service__pb2.InvokeResponse.FromString,
                )
        self.Query = channel.unary_unary(
                '/measurementservice.MeasurementService/Query',
                request_serializer=dio__measurement__service__pb2.QueryRequest.SerializeToString,
                response_deserializer=dio__measurement__service__pb2.QueryResponse.FromString,
                )
        self.Register = channel.unary_stream(
                '/measurementservice.MeasurementService/Register',
                request_serializer=dio__measurement__service__pb2.RegistrationRequest.SerializeToString,
                response_deserializer=dio__measurement__service__pb2.ServerEvent.FromString,
                )
        self.OpenDIOSession = channel.unary_unary(
                '/measurementservice.MeasurementService/OpenDIOSession',
                request_serializer=dio__measurement__service__pb2.DIOOpenSessionRequest.SerializeToString,
                response_deserializer=dio__measurement__service__pb2.DIOOpenSessionResponse.FromString,
                )
        self.ReadDI = channel.unary_unary(
                '/measurementservice.MeasurementService/ReadDI',
                request_serializer=dio__measurement__service__pb2.ReadDIRequest.SerializeToString,
                response_deserializer=dio__measurement__service__pb2.ReadDIResponse.FromString,
                )
        self.WriteDO = channel.unary_unary(
                '/measurementservice.MeasurementService/WriteDO',
                request_serializer=dio__measurement__service__pb2.WriteDORequest.SerializeToString,
                response_deserializer=dio__measurement__service__pb2.WriteDOResponse.FromString,
                )
        self.CloseDIOSession = channel.unary_unary(
                '/measurementservice.MeasurementService/CloseDIOSession',
                request_serializer=dio__measurement__service__pb2.DIOCloseSessionRequest.SerializeToString,
                response_deserializer=dio__measurement__service__pb2.DIOCloseSessionResponse.FromString,
                )


class MeasurementServiceServicer(object):
    """---------------------------------------------------------------------
    The MeasurementService service definition.
    ---------------------------------------------------------------------
    """

    def Invoke(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Query(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenDIOSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadDI(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteDO(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseDIOSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MeasurementServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Invoke': grpc.unary_unary_rpc_method_handler(
                    servicer.Invoke,
                    request_deserializer=dio__measurement__service__pb2.InvokeRequest.FromString,
                    response_serializer=dio__measurement__service__pb2.InvokeResponse.SerializeToString,
            ),
            'Query': grpc.unary_unary_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=dio__measurement__service__pb2.QueryRequest.FromString,
                    response_serializer=dio__measurement__service__pb2.QueryResponse.SerializeToString,
            ),
            'Register': grpc.unary_stream_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=dio__measurement__service__pb2.RegistrationRequest.FromString,
                    response_serializer=dio__measurement__service__pb2.ServerEvent.SerializeToString,
            ),
            'OpenDIOSession': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenDIOSession,
                    request_deserializer=dio__measurement__service__pb2.DIOOpenSessionRequest.FromString,
                    response_serializer=dio__measurement__service__pb2.DIOOpenSessionResponse.SerializeToString,
            ),
            'ReadDI': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadDI,
                    request_deserializer=dio__measurement__service__pb2.ReadDIRequest.FromString,
                    response_serializer=dio__measurement__service__pb2.ReadDIResponse.SerializeToString,
            ),
            'WriteDO': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteDO,
                    request_deserializer=dio__measurement__service__pb2.WriteDORequest.FromString,
                    response_serializer=dio__measurement__service__pb2.WriteDOResponse.SerializeToString,
            ),
            'CloseDIOSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseDIOSession,
                    request_deserializer=dio__measurement__service__pb2.DIOCloseSessionRequest.FromString,
                    response_serializer=dio__measurement__service__pb2.DIOCloseSessionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'measurementservice.MeasurementService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MeasurementService(object):
    """---------------------------------------------------------------------
    The MeasurementService service definition.
    ---------------------------------------------------------------------
    """

    @staticmethod
    def Invoke(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/measurementservice.MeasurementService/Invoke',
            dio__measurement__service__pb2.InvokeRequest.SerializeToString,
            dio__measurement__service__pb2.InvokeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/measurementservice.MeasurementService/Query',
            dio__measurement__service__pb2.QueryRequest.SerializeToString,
            dio__measurement__service__pb2.QueryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/measurementservice.MeasurementService/Register',
            dio__measurement__service__pb2.RegistrationRequest.SerializeToString,
            dio__measurement__service__pb2.ServerEvent.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def OpenDIOSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/measurementservice.MeasurementService/OpenDIOSession',
            dio__measurement__service__pb2.DIOOpenSessionRequest.SerializeToString,
            dio__measurement__service__pb2.DIOOpenSessionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadDI(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/measurementservice.MeasurementService/ReadDI',
            dio__measurement__service__pb2.ReadDIRequest.SerializeToString,
            dio__measurement__service__pb2.ReadDIResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WriteDO(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/measurementservice.MeasurementService/WriteDO',
            dio__measurement__service__pb2.WriteDORequest.SerializeToString,
            dio__measurement__service__pb2.WriteDOResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CloseDIOSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/measurementservice.MeasurementService/CloseDIOSession',
            dio__measurement__service__pb2.DIOCloseSessionRequest.SerializeToString,
            dio__measurement__service__pb2.DIOCloseSessionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
